### ISSUE TITLE
Remove dirs requirement for client with wasm32 targets

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#1115]
The client uses the `dirs` crate to get the home directory and the profile for the connection. wasm32 doesn't have access to the filesystem.

Do something (stub it out?) to fix this.

Subtask of #989.

**Comment by nicholastmosher** [comment]
We could probably enhance the config API in order to help support this. Broadly, we can either create a connection configuration in two ways:

- By loading the config from a file `~/.fluvio/config`
- By programmatically constructing a config

Probably what we want to do is add some `cfg`'s so that when building for wasm32, the first API is simply not available and callers need to programmatically construct a config.

**Comment by nicholastmosher** [comment]
I believe this was fixed by #1132
