### ISSUE TITLE
CI: Docker publishing should not happen in the Cluster Test

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1205]
see: https://github.com/infinyon/fluvio/runs/3004264042?check_suite_focus=true.

It should be happen as last step in the workflow when all other steps are successful. But currently, it is publishing even thought other test `Kubernetes cluster upgrade test` is still happening

**Comment by nicholastmosher** [comment]
I believe this is expected behavior. This "publish image" step publishes the image tagged with `infinyon/fluvio:VERSION-GITHASH`, which is not an image that gets pulled by clients. This is so that we "save" the exact image that has been tested and stage it to be released.

![image](https://user-images.githubusercontent.com/4210949/124757103-41618600-defb-11eb-9031-7e4fc2a9f230.png)

It is not until the `publish.yml` workflow runs (after merge to master) that this image is taken and re-tagged as `infinyon/fluvio:VERSION`, at which point it is "released" and will be pulled by clients.

![image](https://user-images.githubusercontent.com/4210949/124757341-779f0580-defb-11eb-99a9-4b78b0a5ca42.png)

> https://github.com/infinyon/fluvio/runs/3002981692?check_suite_focus=true

**Comment by nicholastmosher** [comment]
This pattern is left over from since before we used to upload the docker images to `actions/upload-artifact`. Now that we do upload it as an artifact, we can create a new job after all the tests that just downloads the docker image artifact and pushes it to Docker hub.
