### ISSUE TITLE
Add Producer longevity test to CI

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#1287]
I use the following code 

```
import paho.mqtt.client as mqtt
from fluvio import Fluvio

# The callback for when the client receives a CONNACK response from the server.
def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))

    # Subscribing in on_connect() means that if we lose the connection and
    # reconnect then subscriptions will be renewed.
    client.subscribe("/hfp/v2/journey/#")

# The callback for when a PUBLISH message is received from the server.
def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))
    producer.send_record_string(msg.topic+","+str(msg.payload), 0)


# Connect to fluvio
fluvio = Fluvio.connect()
producer = fluvio.topic_producer("mqtt")

# Connect to mqtt
client = mqtt.Client()
client.on_connect = on_connect
client.on_message = on_message

#client.connect("mqtt.eclipseprojects.io", 1883, 60)
client.connect("mqtt.hsl.fi", 1883, 60)

# Blocking call that processes network traffic, dispatches callbacks and
# handles reconnecting.
# Other loop*() functions are available that give a threaded interface and a
# manual interface.
client.loop_forever()
```

After about 1 hour, it gets disconnected:

Jul 22 23:50:58 ubuntu python3.8[2194]:     self.on_message(self, self._userdata, message)
Jul 22 23:50:58 ubuntu python3.8[2194]:   File "/home/ubuntu/mqtt/client.py", line 15, in on_message
Jul 22 23:50:58 ubuntu python3.8[2194]:     producer.send_record_string(msg.topic+","+str(msg.payload), 0)
Jul 22 23:50:58 ubuntu python3.8[2194]:   File "/home/ubuntu/.local/lib/python3.8/site-packages/fluvio/__init__.py", line 159, in send_record_string
Jul 22 23:50:58 ubuntu python3.8[2194]:     return self._inner.send_record(buf.encode('utf-8'), partition)
Jul 22 23:50:58 ubuntu python3.8[2194]: _fluvio_python.Error: Fluvio socket error
Jul 22 23:50:58 ubuntu python3.8[2194]: Caused by:
Jul 22 23:50:58 ubuntu python3.8[2194]: time out in serial: 0 request: 79982
Jul 22 23:50:58 ubuntu systemd[1]: mqtt.service: Main process exited, code=exited, status=1/FAILURE
Jul 22 23:50:58 ubuntu systemd[1]: mqtt.service: Failed with result 'exit-code'.

**Comment by tjtelan** [comment]
This issue is not specific to the content of the traffic, but rather the instability when a producer has accumulated 50K+ records.

To resolve this issue, we will create a producer longevity test.

To start, we'll connect to an external cluster, and we will produce a single record per second. We'll cap this test to run for an hour to start and we can increase the runtime if the github runner environment proves to be stable for longer runs.

For reference to get to 50K records, at 1 record/second, we'll need to run for 13.3 hours.

(The github runners will run for 72 hours. Eventually we're going to want to aim for at least 24 hours, and increase the throughput)

**Comment by ajhunyady** [comment]
We should produce closer to 1k message per second. That will make fail faster and it's a more realistic use case.

**Comment by ajhunyady** [comment]
MQTT client receives around 50 messages per second.
