### ISSUE TITLE
Upgrade Test need to check version

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1415]
To ensure platform has upgrade to right version

**Comment by tjtelan** [comment]
One type of test not being performed in CI is upgrade using this bundled helm chart. When we use the `--develop` flag, we're providing a value for the docker image.

But when we just run `fluvio cluster upgrade`, we possibly end up using the version in the chart as the platform version we search for. Coincidentally, that version is `0.9.0` currently.

https://github.com/infinyon/fluvio/blob/38bc8bc6dcefb6ede0ef9022a471aa12f42f7a72/k8-util/helm/fluvio-app/Chart.yaml#L5
https://github.com/infinyon/fluvio/blob/38bc8bc6dcefb6ede0ef9022a471aa12f42f7a72/k8-util/helm/fluvio-sys/Chart.yaml#L5

```
Aug 12 14:56:53.984 DEBUG install_fluvio{namespace="default"}:wait_for_fluvio_version{config=FluvioConfig { endpoint: "172.21.0.2:30571", tls: Disabled }}: fluvio_cluster::start::k8: Existing platform version is different than platform version platform=0.9.0 platform_version=0.9.3
```

We need to do is ensure that the testing flow more closely resembles the release flow, since typical users won't use `--develop`.
