### ISSUE TITLE
CLI - Fluvio release channels

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#1663]
Currently in order to deploy version, we need to type:
```
 fluvio cluster start --image-version latest --help
```

This is error prone.  We need to have user to test development version quickly

**Comment by sehz** [comment]
Try to debug #1662

**Comment by sehz** [comment]
@tjtelan to scope this out

**Comment by tjtelan** [comment]
I think we should go the "channel" route. We can manage the CLI details in the config (e.g. `~/.fluvio/config`). I'd like to not touch the installer, which I believe is possible. The workflow we want exists today, but it's just really complicated.

There are a few logistical detail to straighten out.

### What are channels?
Channels are an abstraction to manage switching between multiple binaries of different versions of Fluvio on the same host.

This is a significant workflow to support for devs and contributors when both working together on validating fixes, since dev artifacts are produced but not easily shared in the same way official releases are.

### What channels do we need?

* I think we should keep this simple for now and handle what our installer script does: `dev`, `stable` and a version number (effectively, this would be version pinning. Stretch goal.).

### How do you enable/disable/delete channels?

* I want to keep track of channels via the config in `~/.fluvio/config`. We can hardcode the set of channels, and provide a context switcher within `fluvio profile`. This will allow us to confidently handle `fluvio upgrade` because we know what channels are enabled

### What are the developer expectations for being on a channel?

* `fluvio cluster start` is the main workflow that should "just work" while being on any channel.
  * Although, it would be acceptable if the `dev` channel checked for updates. I don't want to get into the details of keeping multiple versions of `dev` bc those are keyed on git commits. Let's not. The `dev` channel is on a rolling-release cadence.
* `fluvio version` and `fluvio profile` might want to print the current channel.
* `fluvio upgrade` should update all of the channels (that have been enabled), similar to how `rustup` works. Since we use the `--develop` flag in a few contexts, that can be the behavior for when we're in a `dev` channel.
  * Running `fluvio upgrade` while on a version number channel should download updates, but then remind the user what channel they are in and how to switch.

### What actually happens when you switch channels?

I haven't formed an opinion on the implementation yet. What I'd like to do is keep channel binaries alongside the fluvio config in some manner. This gives me some space to make assumptions about the environment I'm in, because our CI doesn't always install the binary to `~/.fluvio/bin/fluvio`. I think this is ok, bc our extensions are always expected to be in the same place. As will our channel binaries.

My first instinct is we cannot just swap out binaries in PATH because . It might be ok to `exec` from one fluvio binary to a channel binary

**Comment by tjtelan** [comment]
Here's an update to how I'm going to prototype this after meeting with team

* `fluvio update` is out of scope for prototype
  * Bring up later to design when channel ergnomics are settled
* 2 channels and no user-specified channels to start, keep it simple. `stable` and `dev`
* Allow runtime knowledge to switch between the expected image versions to use, for `fluvio cluster start`
  * e.g., the git sha is part of the version when we use `--devel`, and if we fail to provide this flag, the cluster doesn't start, so if we know we're on a dev channel, automatically use the dev versions so we start correctly.
* Keep a separate directory for extensions of different channels
  * e.g. `~/.fluvio/extensions-dev`
* I think we can do a channel check right before we evaluate subcommands, and then `exec` to the correct binary.
* Keep state of channels in `~/.fluvio/config`
  * Binary location
  * extensions location
  * Current active channel

**Comment by tjtelan** [comment]
Based on some feedback from the team, I'll be modifying this implementation from where I'm at in #2021.

---

`fluvio config channel switch <channel>` is too long of a command. Moving this to be under `fluvio version` is interesting, so I might play around with that.

---

We should factor out channel awareness into some front-end, and then exec to the binary we need to use based on channel. This is how `rustup` works with `cargo`, and we want that kind of user experience.

Just thinking on the keyboard, but this might been creating a new binary crate `fluvio-channel` (for example). When we do an official installation, we will install `fluvio-channel` in the `~/.fluvio/bin/fluvio` location, as well as a `fluvio-stable` which will be the new filename for the CLI we use today.

When we switch to a new channel, we'll do pretty much what I'm doing now. Download appropriate release binaries if they don't exist. When we execute, we'll set some environment variables to let `fluvio-stable` (or whatever channel we're using) be aware enough to know what other flags they need to set.

A reason for this change is to support multiple stable release channels for the CLI rather than the 3 channels we have now.

---

Also, Windows support is required. The only blocker was to implement the workflow using the equivalent of `exec` in Windows. Placing the concerns of channel support away from the main CLI will also be convenient for maintainability.
