### ISSUE TITLE
Installer downloading old version of `fluvio-run`

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2103]
https://github.com/infinyon/fluvio/runs/4797239039?check_suite_focus=true.

With installer outside CI, fluvio-run (in Ubuntu) is:
```
ls -la fluvio-run 
-rwxr--r-- 1 ubuntu docker 49327472 Jan 12 23:28 fluvio-run
```

But in the CI, it is showing the old version
```
-rwxr--r-- 1 runner docker 36237264 Jan 13 00:26 fluvio-run
```

This affects `Mac/M1` which is downloading an older version.

**Comment by tjtelan** [comment]
Turns out the `Release` workflow never updates the `stable` version tag, but we always update the `latest` version tag. Explains why we didn't see this behavior earlier in `CD_Dev`. We're probably missing the `stable` bump for other packages too. 

https://github.com/infinyon/fluvio/blob/fbc7d10a3989e2a24dd2012b7acd23e3e387cb24/.github/workflows/release.yml#L347-L350
