### ISSUE TITLE
Connector log from an invalid connector should return an error

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio#2161]
No connectors configured:

```
$ fluvio connector list
no managed connectors
```

Use log command:

```
$ fluvio connector logs foo
```

The command just returns, it should say:
`Error: Connector foo does not exist`

**Comment by Afourcat** [comment]
Hello,
If nobody is working on this issue, I have implemented a fix.

## Fix
To fix the issue, I return a `CliError::InvalidArg(...)` when no connector is matching the user's requested name.
This leads to this example output:
```bash
$ fluvio connector logs undefined
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/fluvio connector logs undefined`
Error: 
   0: Invalid argument: Connector undefined does not exist
```
Is the `CliError::InvalidArg` the right error in your opinion?

## Bug
When implementing the fix, I realized that there is a bug, at least on the master branch.

### Reproduce
> minikube version: 1.25.1
> kubectl version: Major:"1", Minor:"23", GitVersion:"v1.23.3"
> fluvio CLI version: commit: 0b991889205213c3a043c9ce7a9d0864b7eb6737

Let's suppose I have previously created a single connector named 'cat-facts'.
And I want to read its logs thanks to the CLI.
```bash
$ fluvio connector logs cat-facts
# no output
```
There is no output to the previous command.
But, if I understand well, the expected output should be the same as:
```bash
$ kubectl logs cat-facts-[ommited]
2022-02-12T14:40:55.099275Z  INFO http: Initializing HTTP connector
2022-02-12T14:40:55.099293Z  INFO http: interval=10 method=GET topic=cat-facts output_parts=body output_type=text endpoint=https://catfact.ninja/fact
2022-02-12T14:40:55.101290Z  INFO connect: fluvio::sockets: connect to socket add=fluvio-sc-public:9003
2022-02-12T14:40:55.103999Z  INFO http: Connected to Fluvio
[ommited]...
```
### Fix
I fixed it with this simple edit:
```diff
         let pods = Command::new("kubectl")
-            .args(["get", "pods", "-o=jsonpath='{.items[*].metadata.name}"])
+            .args(["get", "pods", "-o=jsonpath={.items[*].metadata.name}"])
             .output()?
             .stdout;
```
### Cause
As you can see, there is a single quote at the beginning of the jq expression, which was leading to the output of the command starting by a `'`.

> For example, with the a cat-facts connector: `'cat-facts-6b84d6d8c4-kjvd6 fluvio-sc-55955487f4-2kfnq fluvio-spg-main-0`

The output is then split by space. Which is leading to this array.
```rust
["'cat-facts-6b84d6d8c4-kjvd6", "fluvio-sc-55955487f4-2kfnq", ...]
```
Then we find the pod matching the user requested name thanks to the function `str::start_with`:
```rust
// Where self.name is in my case: cat-facts
// And the corresponding pod name is: 'cat-facts
let pod = pods.split(' ').find(|pod| pod.starts_with(&self.name));
```
If the request connector happens to be the first listed by the `kubectl get pods` command, nothing matches and therefore no output is printed.
### Questions
With the current implementation, we can see the log of all pods because we are not matching the `app=fluvio-connector` label. So if we use the fluvio CLI the following way:
```bash
$ fluvio connector logs fluvio
# Full logs of one of the fluvio SC or SPG.
```
To fix this problem, I added the `--selector "app=fluvio-connector"` argument to the `Command`.
```diff
-            .args(["get", "pods", "-o=jsonpath='{.items[*].metadata.name}"])
+            .args([
+                "get",
+                "pods",
+                "--selector",
+                "app=fluvio-connector",
+                "-o=jsonpath={.items[*].metadata.name}",
+            ])
```

Should I make a new issue/PR for this bug, or is it acceptable to fix the problem within this one? 

## Another Potential Bug
Even with the previous fix, there is another problem.
If we create 2 connectors, for example:
- cat-facts
- cat-facts-2

Because we are finding the pod thanks to the `str::start_with` function, there is a possibility of always matching the second one.

I should be able to write a fix, but I need to think about the implementation a little bit more.
Do you want me to fix this one within the same PR?

Does both my fixes sound right? If yes, I will [make the PR](https://github.com/Afourcat/fluvio/tree/feature/fluvio-cli-error-when-undefined-connector) as soon as possible.

Thank you,

**Comment by sehz** [comment]
Thanks for looking at this issue.  Yes, it's ok to fix this in the same PR.   You can resolve the duplicate name by matching `name` metadata.

**Comment by Afourcat** [comment]
In my testing environment, `metadata.name` contains postfixed generated strings.
```bash
$ fluvio connector list
 NAME         VERSION  STATUS 
 cat-facts    latest   Running 
 cat-facts-2  latest   Running 
 lion-facts   latest   Running
$ kubectl get pods -o=jsonpath='{.items[*].metadata.name}' | tr ' ' '\n'
cat-facts-2-69449c98bf-shkv9
cat-facts-6b84d6d8c4-mlnj5
fluvio-sc-55955487f4-2kfnq
fluvio-spg-main-0
lion-facts-5bb87c847c-jb979
```
I tried to find another field in the pod description, but nothing seems to do the trick.
So, I don't know if it's a constant but it seems that generated strings are always (10 + 5 + 2 dashes) of length

So I implemented the following function:
```rust
fn is_matching_connector_name(&self, pod_name: &str) -> bool {
    const GENERATED_STRING_SIZE: usize = 17;

    let connector_name = &pod_name[..pod_name.len() - GENERATED_STRING_SIZE];
    connector_name == self.name
}
```
And called it as the find predicate.
```rust
let pod = pods
    .split(' ')
    .find(|pod_name| self.is_matching_connector_name(pod_name));
```
Which fixes the problem,
I'm wrong somewhere?

---
I also found out that connectors with a name greater than 63 chars are not working, because the pods' name seems to be limited. But not consumers' names.
It also seems that, if the name of the consumer is 63, 5 chars are trimmed off and replaced by a generated string.

```
----------------------------------------------------------v
lions-facts-skdjflaksjdfkjqwkejqkwjerkjsadkjflajkqwjerkqjw|htsp6
lions-facts-skdjflaksjdfkjqwkejqkwjerkjsadkjflajkqwjerkqjw|kerqw
```

Thank again,
