### ISSUE TITLE
Exactly Once Delivery semantics 

### ISSUE THREAD

**Issue by vipierozan99** [infinyon/fluvio#2981]
I haven't seen discussion around this topic:

- Is Exactly Once Delivery something to think about for fluvio? 
- Is it one the roadmap? 
- Is it in the scope of the project? 
- If not, does it make sense in a library?

**Comment by sehz** [comment]
Hi, 

Exactly-once delivery is on our horizon and is frequently requested features.  It is complex subject with two different behavior guarantees: (1) Transaction guarantee (2) Idempotency Guarantee.    Building these behavior is not something can be done in library since they requires managing in-flight data semantics.   However, we want to build these with minimum core capability such that they can be extended with SmartModule since these behavior are highly dependent on domain logic.

More concrete use cases would make it easier to build core capabilities.  Would love to have you describe your use cases to prioritize which behaviors to put into the roadmap.
