### ISSUE TITLE
feat: apply SmartModule  for producer

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#2988]
Currently, SmartModule transformations can be applied to consumers.   It should apply to producers as well.  This allows more flexible data transformation from CLI.

The transformation runs in the SPU

**Comment by crajcan** [comment]
Is this requesting the client-side transformation described [here](https://github.com/infinyon/fluvio-website/blob/229a54317c240522bff12544da74ca14af94186a/content/docs/concepts/transformations-chain.md?plain=1#L8-L9)?

Or is this requesting that the SPU handle the transformation before committing the data?

**Comment by crajcan** [comment]
A couple questions: 

**Aggregate SmartModules**

Should this feature support aggregate SmartModules? I can think of a few different ways they could be applied:

1. Apply the SmartModule to each batch then commit the accumulator. This would be useful if you wanted to save space by committing the sum of a batch of integers instead of the entire batch, for example.

2. Apply the SmartModule to each record, using the last record in the partition as the initial accumulator. This would be useful if you wanted each record committed to represent a cumulative sum. 

3. Apply the SmartModule to each record, but rely on the producer to provide the initial accumulator.

**Compression**

Should SmartModules be applied when a compression algorithm is specified? Batches would have to be decompressed, transformed, and then compressed again before committing.

**Comment by sehz** [comment]
Nice progress on PR.   Answer to your questions:
```
Aggregation:  I think so, all SmartModule API should be used
Compression:  Yes, it should work in compression cases as well but that is transparent to SmartModule so don't believe there is additional work needed. 
```

**Comment by crajcan** [comment]
[This](https://github.com/infinyon/fluvio/pull/3014) is ready for review now. I'm not sure anyone saw it because it's pretty far down the list.

No rush at all though!

**Comment by sehz** [comment]
Very nice work.  This is tremendous achievements

**Comment by sehz** [comment]
Just to set context.  All transformations happen in the SPU (except connectors) now.   There is option to apply transformation in the fluvio client but it is not enabled by default.

**Comment by ajhunyady** [comment]
There is value to both flavors:
1. Apply to SPU (as done by this PR) when you want to share producer transformations across all clients. Ideally, this type of transformations should be applied to topic to remove ambiguity, however this PR is valuable as is.
2. Apply to Producer client, for edge processing, to filter-out irrelevant data at the source.

**Comment by sehz** [comment]
Done
