### ISSUE TITLE
address usability issues with `hub`, `cdk` and `smdk``smartmodule`

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#3187]
`fluvio hub download` command has couple of usability issues:
- it only can download `smartmodule` requiring different commands for `connector`
- it requires to navigate to different command.

Instead we should add new command `download` to `smartmodule`.  So to download smartmodule: 
```
$ fluvio smartmodule download <sm_id>
```

Other clean up: `--local` moved to separate command in the `hub` 

**Todos**
- [x] https://github.com/infinyon/fluvio/issues/3291

**Comment by ajhunyady** [comment]
Let's hold off on this. @drc-infinyon is working on a use-case centric CLI hierarchy. We should have a comprehensive proposal shortly.

**Comment by drc-infinyon** [comment]
![cli-usability](https://github.com/infinyon/fluvio/assets/122817612/66ba2ae0-2a33-44d4-a869-14b722d97486)

**Comment by EstebanBorai** [comment]
> ![cli-usability](https://github.com/infinyon/fluvio/assets/122817612/66ba2ae0-2a33-44d4-a869-14b722d97486)
> 
> 

Very cool!

**Comment by tjtelan** [comment]
> ![cli-usability](https://user-images.githubusercontent.com/122817612/238082595-66ba2ae0-2a33-44d4-a869-14b722d97486.png)

This is a small tangent to the content, but related to the usability issues in the CLI regarding the structure of the subcommands.

`fluvio hub sm list` - I'm not convinced this is a good command pattern to keep, for the same reason you want to get rid of `fluvio hub connector`. The grammar is inconsistent, and it was confusing for users. I don't feel like keeping the pattern, but just with smartmodules, it makes it easy to self-discover what actions are available to do.

Take the kubernetes CLI `kubectl` as an example. It's interface is consistent and easy to navigate as you travel deeper through the subcommands because it gets more specific at each level because the CLI is a taxonomy. It makes it really easy to translate a concept of what you in order to build the correct command **for any resource**. 

---

> For reference below, all of the cli commands can be seen grouped together here: https://github.com/infinyon/fluvio-website/blob/master/data/cli-commands.yml - I think it helps illustrate the grammar we use in the CLI.

Mostly our command structure looks like this:
`fluvio <context> <verb>`

We break this pattern when we go to another level in `fluvio cluster` and in `fluvio hub`, and it doesn't make any sense why. IMO, it leads to inconsistent words for functionally similar actions, and is generally confusing for setting user expectations.

For example, why is `fluvio cluster start` and `fluvio cluster status` at the same level as `fluvio cluster spu`? 

```
fluvio <context> <spu|spg> <action>
fluvio cluster spu register
fluvio cluster spu unregister
fluvio cluster spu list
fluvio cluster spg
fluvio cluster spg create
fluvio cluster spg delete
fluvio cluster spg list
```

Would we ever want to not list? To continue the pattern, would we add another resource as `fluvio cluster <example-cluster-component>`? What is the difference between `create` and `register` and **does this distinction matter to users**?

Too much thinking involved, and I don't want to think this hard.

---

This should be 
`fluvio <context> <action> <resource>`

So like:
```
fluvio cluster list spu|spg
fluvio cluster create spu|spg
fluvio cluster delete spu|spg
```

And for Hub, this would be:

```
fluvio hub list sm|conn|etc
fluvio hub download `sm|conn|etc
```

It makes the subcommand hierarchy consistent and scalable. It's much easier to set documentation and functionality expectations for users as the system grows and it's easier to maintain as a developer too - because with the best of intentions, naming and consistency still is hard.

Everyone wins when the grammar is more predictable. And it should be for the user's benefit when the grammar is inconsistent because it otherwise makes it hard to self-discover or raises the barrier to inform about the existence of functionality.

**Comment by drc-infinyon** [comment]
This is outstanding @tjtelan. Thanks for the detailed presentation of the rationale.

**Comment by EstebanBorai** [comment]
@tjtelan great feedback! I agree with the direction you are proposing here.

Perhaps we could begin splitting some work and define a set of actionable to achieve this @drc-infinyon?
I think we could use the nomenclature proposed by TJ as a guide:

```
fluvio <context> <action> <resource>
```

And define what needs to be done for each `context`, then begin with re estructure bits.

**Comment by ajhunyady** [comment]
This is quite a big change, and we don't have the luxury to do both.
For now, let's continue with our current paradigm:

```
fluvio hub connector list
fluvio hub sm list
```

When we have more time, we can add alternative paths.
