### ISSUE TITLE
[Bug]: in some conditions, `fluvio consumer -c <id> <topic>` does not record offsets

### ISSUE THREAD

**Issue by digikata** [infinyon/fluvio#3963]
**What happened**
In some cases, `fluvio consumer -c <id> <topic>` does not record offsets

**Expected behavior**
A consumer should record offsets when a consumer id is defined at the cli.

**Describe the setup**
- fluvio 0.11.6 stable
- tested bug on Linux and Macos

**How to reproduce it (as minimally and precisely as possible)**
1. `fluvio cluster start`   start a local cluster
2. `fluvio topic create test`
3. `fluvio produce test` # create 3-4 records
4. `fluvio consume test -c c_works -Bd`  this creates an offset
5. `fluvio consume test -c c_notcreated` this consumes offsets from the end, leave running for next steps
6. `flvuio produce test` # create 3-4 records
7. `fluvio consumer list` shows a `c_works` offset, but no `c_notcreated` offset

**Comment by galibey** [comment]
How the `auto` strategy works:
1. Commit happens when the next record is yelded.
2. Flush happens after a certain interval (10 seconds now by default).
3. Flush happens after a commit is triggered (see `item 1` in this list).
4. Both commit and flush are called when the stream is finished.

So, when you use `-d` option, both commit and flush called in the end and it stores the last read offset regardless of all other logic.

Without `-d` it quickly read all records, the flush interval has not passed yet. Another record (after 10 seconds) would store the offset. On top of that, most probably, `Ctrl+C` was pressed to stop consuming. We don't have a signal handler, so it shuts down the process without giving a chance for the consumer to invoke `item 4` logic in the list.

As a suggestion, we could add a handler for `Ctrl+C` signal to `consume` that will gently stop consuming allowing to flush offsets if needed. Wdyt @digikata

**Comment by ajhunyady** [comment]
Is the flush interval configurable?

**Comment by galibey** [comment]
> Is the flush interval configurable?

On CLI - no, only on API level.

**Comment by ajhunyady** [comment]
Ok, I’m thinking the SPU should detect a disconnect from the consumer and flush. It’s probably the solution you are suggesting above.

Without handling this case, the feature feels brown.

**Comment by galibey** [comment]
> Ok, I’m thinking the SPU should detect a disconnect from the consumer and flush. It’s probably the solution you are suggesting above.
> 
> Without handling this case, the feature feels broken.

The flush here is from the client to the SPU. Any detections on SPU side are irrelevant here.

**Comment by digikata** [comment]
I think I would shorten the default flush interval, but a signal handler sounds good too.  

A flush w/ signal handling sounds good too.  ctrl+C is a little tricky because you often want to preserve the interrupt behavior at least on a second ctrl+c.    Maybe a shutdown with flush on a Ctrl+D fits a graceful shutdown and flush a little better - and we leave ctrl+c alone?

**Comment by sehz** [comment]
disconnect or end of consumer session should trigger flusg

**Comment by galibey** [comment]
> I think I would shorten the default flush interval, but a signal handler sounds good too.
> 
> A flush w/ signal handling sounds good too. ctrl+C is a little tricky because you often want to preserve the interrupt behavior at least on a second ctrl+c. Maybe a shutdown with flush on a Ctrl+D fits a graceful shutdown and flush a little better - and we leave ctrl+c alone?

We would preserve interruption with Ctrl+C of course. We can just give some time (1-2 seconds for example) to flush and after that period exit. And, the second Ctrl+C also can force exit immediately.  So, single Ctrl+C - 1 second graceful period and exit, double Ctrl+C - exit immediately. Something, like this.

**Comment by galibey** [comment]
> disconnect or end of consumer session should trigger flusg

It does. The `SIGINT` signal does not leave much space for any code execution.

**Comment by ajhunyady** [comment]
Can we also change the flush interval to `2 sec` ?

**Comment by galibey** [comment]
> Can we also change the flush interval to `2 sec` ?

https://github.com/infinyon/fluvio/pull/3976
