### ISSUE TITLE
move sc and spu as separate plug-in

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#427]

**Comment by nicholastmosher** [comment]
Right now the SC and SPU components are executed via `fluvio run sc` and `fluvio run spu`. In making them CLI plugins, they will need to have a name such as `fluvio-spu` or `fluvio-sc`, but this clashes with the current `fluvio spu` command right now. We need to decide what names to use.

One option is to implement the changes described in #367 and instead of having `fluvio spu list`, we could have `fluvio list spu`, which then frees up the top-level `fluvio spu` command to be used to directly invoke the SPU component, and since SC is already available that would work out nicely.

The other option is to come up with some other `fluvio-something` name for both the sc and spu which are ideally consistent with each other. Maybe something like `fluvio-runspu` and `fluvio-runsc` but that seems kind of dirty.

Can we brainstorm solutions to this?

**Comment by sehz** [comment]
New command extension crate `extension-runner` is created.  This extension only has dependencies to `sc` and `spu`.  Existing `run` command is migrated to this extension:
```
./target/debug/fluvio_runner_cli 
fluvio-runner 0.1.0

USAGE:
    fluvio_runner_cli <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    help    Prints this message or the help of the given subcommand(s)
    run     Run a Streaming Controller (SC) or SPU
```

This run command is embedded in the Fluvio CLI as: `fluvio cluster run`
