### ISSUE TITLE
Pi support to fluvio-package-index

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#529]
The package index should support raspberry pi targets to allow for pi binaries to be uploaded and installed.

**Comment by nicholastmosher** [comment]
Hmm @simlay feel free to assign this to you if you are in the middle of raspberry-pi work already. Another element to the full Pi support is updating the install script to support it. That'll require:

- Testing the install script and making sure that it can correctly identify the architecture of the various Pi's
- Adding the architectures to the `latest` file so that the install script can download the right version

**Comment by nicholastmosher** [comment]
Closed by #1234
