### ISSUE TITLE
CLI: self-update doesn't work

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#617]
Steps produce it:
Install current release or previous release.
Try to perform self update:
```
which fluvio
/home/ubuntu/.fluvio/bin/fluvio
ubuntu@ip-172-31-20-82:~$ fluvio update
🎣 Fetching latest version for fluvio/fluvio...
⏳ Downloading Fluvio CLI with latest version: fluvio/fluvio:0.6.0-beta.2...
🔑 Downloaded and verified package file
Error: 
   0: Text file busy (os error 26)
```

**Comment by nicholastmosher** [comment]
I finally found the [error reference for this](https://www.gnu.org/software/libc/manual/html_node/Error-Codes.html#index-ETXTBSY)

It seems that we are not allowed to overwrite our own executable. I think that the reason this worked before was because we had mix-ups between whether we were going to store the `fluvio` executable in `~/.fluvio/bin/` or `~/.fluvio/extensions`, so probably what happened before was that `~/.fluvio/bin/fluvio` "updated" `~/.fluvio/extensions/fluvio` so there was no collision. Now that we have sorted it out, we are seeing the error.

I think we might want to do a bit of research as to how other self-updating tools work. I'm wondering if it would be sufficient to spawn a different process to do the file overwrite for us.

**Comment by nicholastmosher** [comment]
I'm trying out a new strategy for self-updating where we spawn a new process that performs the update. This new strategy introduces a new hidden flag, `fluvio update --replace=path/to/original/fluvio`. The idea is that a user only ever runs `fluvio update`, but then the CLI will copy itself to a temporary directory and invoke the copy as `fluvio update --replace=<path>`, where `<path>` is the path of the `fluvio` that the user invoked (e.g. `~/.fluvio/bin/fluvio`). When the copy is invoked with the `--replace` flag, it will download the latest version of Fluvio and overwrite the original binary at the given path. This should work no matter where the original `fluvio` binary was executed from.

I've tested it out and it successfully avoids the OS error 26 problem we had before (verified by reproducing the original problem on an ubuntu docker image, then observing the problem disappear after these changes). However, this strategy does seem to introduce a usability problem, which is that the original process spawns the copy process and quits immediately, causing the shell prompt to return immediately. This makes it _appear_ as though the updating process never finishes, because the child process continues printing to stdout after the prompt, and no prompt appears after the child is finished.

https://user-images.githubusercontent.com/4210949/103356211-52c66300-4a7e-11eb-8197-5c08855217d3.mov

> The reason the prompt came back at the end is that I pressed \<Enter>
