### ISSUE TITLE
Detect TCP connection termination in CLI

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#678]
Both produce and consumer has `continuous` way to fetch producer and consumer.  If connection to server goes down, it should immediately terminate it to give user good experience

Scope: If a Fluvio operation (e.g. consume) would stay open, but the connection is terminated, the CLI should gracefully exit and print a message describing what happened.

**Comment by sehz** [comment]
It seems it is possible by turning on client side keep alive and check for error.  

https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die
https://stackoverflow.com/questions/722240/instantly-detect-client-disconnection-from-server-socket

**Comment by nicholastmosher** [comment]
Test if this is still a problem

**Comment by simlay** [comment]
https://github.com/infinyon/fluvio-socket/pull/22 should have helped with this but because there's a new enum in [`FlvSocketError`](https://github.com/infinyon/fluvio-socket/blob/229ff6cf4e74fa59017a502c939fb4b574aa5959/crates/socket/src/error.rs#L13), the auth workspace doesn't like it due to the [`map_err`](https://github.com/infinyon/fluvio/blob/2b050124a2fd286e87f069e0afbb5c8c077e08d5/src/auth/src/x509/authenticator.rs#L63-L67). I didn't think it was a breaking change with https://github.com/infinyon/fluvio-socket/pull/22 but maybe I was wrong.

**Comment by nicholastmosher** [comment]
We need some lower-level machinery updates in order to gracefully handle the producer case of this issue. For now it should be sufficient for the CLI to timeout and print a message which is what happens today.
