### ISSUE TITLE
CLI: `fluvio consume` should give user feedback

### ISSUE THREAD

**Issue by nacardin** [infinyon/fluvio#700]
From @ajhunyady:

We had quite a bit of discussion about this, we all fell into the trap thinking that there is a bug in the system because we forgot to pass -B.
By default the consumer is waiting for new messages, which seems reasonable but not all that intuitive. For new users it seems like something went wrong and the system hangs.

The main question is who is the user for this command? Is it always users or there could also be scripts?
I would assume, we expect users, in which case we should provide some level of feedback. Maybe read the HOL and say something to the extent "2345 records stored" then "Waiting for new records... ".

**Comment by nacardin** [comment]
I agree, when consume is called by a user, it should indicate offset and that it is waiting for new records. Creating separate issue to discuss consume cli.

**Comment by nicholastmosher** [comment]
In the CLI we have a notion of "interactive mode", which happens when the user is sitting and watching the command on their terminal, rather than piping the output somewhere. We can detect which case is happening.

I think a good solution for this would be:

- In "interactive mode", print a notice on stderr to the effect of "Waiting for new records to arrive. To see all records, use -B"
- Don't print anything in non-interactive mode, so that the messages don't end up in somebody's records file
