### ISSUE TITLE
Make a better plan to deal with protocol upgrades

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#717]
#706 cleaned up some tech debt but caused a protocol update and so now current master doesn't work with cloud.

If we update the fluvio instances on cloud, this will result in current clients not working with a `FlvSocketError { source: IoError { source: Custom { kind: InvalidData, error: "PlatformVersion is not valid semver" } } }`

One suggestion is to have a module inside of the dataplane crate that is the older version by [renaming the dependency in Cargo.toml](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html?highlight=rename,depende#renaming-dependencies-in-cargotoml)

**Comment by nicholastmosher** [comment]
I think that there are two problems at play here. One is: how do we manage the versions of the crates that communicate using different versions of the protocol. I think that is what you're getting at with your suggestion to rename the module dependency. I think the other problem is that we actually need to ensure that the protocol and the encoding scheme guarantee a stable version field that will be the same forever. Right now we have a "Platform Version" field that is sent in certain requests, but what we experienced recently was that the platform version was not stable because a change in the encoding of another item caused a shift in the byte offsets of everything else in the message, causing the platform version to essentially become unreadable.

I think it may be a good idea to think about defining a special protocol-version header. This header would be well-defined to have plenty of room for incrementing the version scheme (At least 16 bits, maybe more) and should not rely on the `Encode` or `Decode` auto-derive implementations (so that it does not accidentally get changed in the future). Then, the clients and servers communicating over the protocol will always be able to know what version of the protocol the other is using. In the case of breaking changes, we can use the trick of putting an older client dependency into a module in newer client versions.
