### ISSUE TITLE
better logger: RFC

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#81]
New Logger should have following requirements
- support key/value format
- preserve ordering for async
- multiple output
- support up to 10 or more levels (similar to Golang)
- provide compatibility with existing logger trait

**Comment by nacardin** [comment]
Is there a doc that lists the log levels in Golang?

**Comment by sehz** [comment]
so in the kubectl, there are 10 levels:  https://kubernetes.io/docs/reference/kubectl/cheatsheet/. 
It uses https://github.com/go-logr/logr

**Comment by nicholastmosher** [comment]
The async requirement on this immediately makes me think of `tokio-trace` that I saw presented at [this rust meetup](https://youtu.be/j_kXRg3zlec). It's maintained by [the tokio project](https://github.com/tokio-rs/tracing), but notably:

> `tracing` is maintained by the Tokio project, but does not require the tokio runtime to be used.

Therefore it should be possible to work it into the `flv-` suite regardless of whether `tokio` or `async-std` is being used. 

Tokio-trace is essentially a context-aware, async-friendly event tracker (I say "event tracker" because I don't think the creators consider it exactly a "logging framework", but I think it can be used in a similar spirit). It works similarly to a logging framework and even has some amount of [cross-compatibility with existing Rust logging utilities](https://github.com/tokio-rs/tracing/tree/master/tracing-log) though I don't know to what extent. I'm going to read up more on tokio-trace and see if I can get a sample of it working in fluvio.

Does anybody have any recommendations as to a particular fluvio crate which is easy to invoke and would experience instances of async context-switching pretty often? That might be a good first testing ground for this.

**Comment by sehz** [comment]
I think logging and tracking are 2 different features.   However, It is an excellent idea to add tracing support.   The crate 'flv-sc-core' is good candidate.   Also,  it would be interesting idea to use fluvio to collect tracing output from other Rust applications.

**Comment by nicholastmosher** [comment]
@sehz should we consider this closed by #154 and the handful of other tracing PRs?

**Comment by nicholastmosher** [comment]
I'm going to close this and if there's anything we'd like to add we can open a new issue.
