### ISSUE TITLE
Phase 1a Client for Smart Streams - ConsumerBuilder and SmartStreamBuilder

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio#817]
For the first step, we're going to make the client work using a wasm binary.

Assume that this is compiled to wasm:
```rust
#[wasm_bindgen(type="filter")]
/// Filter to check if the message contains a number
pub fn has_number(value: &[u8]) -> bool {
    let message = str::from_utf8(value).unwrap();
    return !message.chars().all(char::is_numeric);
}
```

I personally think the builder pattern of something like:
```rust
fluvio::consumer::ConsumerBuilder::new().filter(SmartStreamBuilder::from_bin_path("sf1.bin").build()?).build()?
```

But I'm open to other methods.

This builder should also check that the `sf1.bin` conforms to our convention - something like "has a filter extern fn" before sending it to the SPU.

Subtask of #816.

**Comment by nicholastmosher** [comment]
I think that API design is headed in the right direction but there are a few things I think we can improve or that need more thinking:

I think we should certainly have a fluid interface like that, but I'm not convinced that a builder within a builder is the best we can do. One thing I'm seeing is that the `.filter()` method is actually part of the outer builder type, when it feels like`.filter` should belong to something modeled like an iterator. The biggest thing I'm concerned about here is that it feels like it will not be composable. What if you wanted to apply one filter after another? Two problems I immediately see:

- If `.filter()` is really a builder method in the typical sense, then calling it twice would overwrite the first value (I know we can choose that semantics, but as a user familiar with builder patterns that would be what I expect, and it doesn't make sense here).
- In the `SmartStreamBuilder`, we have another `.build()?`, which seems ugly and maybe unnecessary right there. I think we can do something more lazily, so rather than validating right away (e.g. making sure the file can be opened and read immediately), we can just store it as a data structure, saying "when you build the full smart stream definition, then try to load the wasm bin file". That could be an easy way to get rid of the inner `.build()?`.

I guess some takeaways:

- I think creating a SmartStream should definitely be made to feel like an iterator if we can do it
- If we end up needing a builder somewhere, we shouldn't need a builder-within-a-builder

**Comment by ajhunyady** [comment]
We need to be able to chain an order filters and later on maps, transformations, etc.

**Comment by simlay** [comment]
> I guess some takeaways:
> 
>     * I think creating a SmartStream should definitely be made to feel like an iterator if we can do it
> 
>     * If we end up needing a builder somewhere, we shouldn't need a builder-within-a-builder

@nicholastmosher, yes, the iterator functionality won't be lost. Using the `StreamExt` trait, it'll act the same way (`while let Some(_) = my_stream.next().await`). The stream will configured/built before it's iterated on.

I originally wrote `add_filter` over `filter`. I dunno why I changed it back to `filter`.

I like the ConsumerBuilder idea because we will want to `add_filter`s, `add_map`s, and `add_reducer` (or something like it). It's composable and extendable.

The `StreamBuilder` (the builder within the builder), I'm less tied to. I suppose we could have a `SmartStream::from_bin_path` could just return a result for success or not on loading the binary (and maybe checking that it fits the convention).

> We need to be able to chain an order filters and later on maps, transformations, etc.

@ajhunyady Yup, I just forgot about that minor detail. I originally wrote `add_filter` in the simple example with the goal of being able to add more of them.
