### ISSUE TITLE
Separate Fluvio cluster components into an independent plugin

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio#866]
We are beginning to run into problems building the CLI and the cluster components (SC and SPU) together. The latest problem is trying to build for the Raspberry Pi targets. If we split these into multiple binaries, we can tackle these problems separately. Since we have the infrastructure for custom plugins on packages.fluvio.io, it would work nicely to distribute the cluster components as an independent binary plugin.

The main question to be resolved here is what we should call the plugin, since that will have an impact on how it is invoked from the CLI going forward. I think an easy candidate would be `fluvio-run`, so we could run the SC and SPU as `fluvio run sc` and `fluvio run spu`. If anybody has any objections or other preferences for this, please comment below.

**Comment by sehz** [comment]
1. Need to remove `SPU` and `SC` from `Cluster` as dependencies.
2. Cluster should minimize dependencies to `fluvio` since we only need config.  `fluvio` separate into different feature flags.  For example, cluster only needs `config`
3. If we have `run` extension, we need to have API to run and invoke extension from another extension.  For example, `fluvio start --local` need to find and `run` extensions
