### ISSUE TITLE
GitHub Action: Release Test flow

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#929]
Should ensure fluvio release works.  This should be run after
* Release
* Latest Release

**Comment by nicholastmosher** [comment]
I think with the new release flow we do not need this, do you agree @sehz? If so feel free to close

**Comment by sehz** [comment]
Point of this job is to ensure release is done correctly (ensure image/chart/bin is published).   Do we have similar job?

**Comment by nicholastmosher** [comment]
I don't know if we have one already. I would imagine that this would be something useful to check during the hourly tests (e.g. make sure we can pull CLI, docker, helm and set up a cluster successfully) if we don't already

**Comment by tjtelan** [comment]
The last piece missing from this task is handling the rebase from `master` to `stable`.

I was thinking we could use Bors to manage this. The idea is based on how the Rust project appears to do their own releases. We'll create a PR to merge from master to stable, and Bors will run the Release workflow, and finally merge to stable. In my opinoin, since #1056, we should feel some confidence around allowing Bors to retry until it succeeds.

The manual pieces remaining (TODO: Create issues for the automatable tasks):
* Publishing crates
  * This can probably be automated if we define the dependency order
  * We can prepare for the success of this job if we `--dry-run` on merges to `master`.
* Updating `CHANGELOG.md` in repo
  * We want to only include PRs that are public facing. Minimize the number of administrative PRs.
* Editing Github Release changelog section for new releases
  * Specifically, delete any notes for releases that don't match the new version)
* Closing out project milestones

**Comment by tjtelan** [comment]
Closing.

Our publish and release GH action workflows are idempotent. We now treat RELEASE.md, or individual tracking issues as checklists for managing the release flow.

The last missing pieces from this issue are being tracked here:
* #1026 (Rebasing the stable branch)
* #1397 (Automate crates publishing)
