### ISSUE TITLE
Support upgrade for local cluster with persistent data

### ISSUE THREAD

**Issue by tjtelan** [infinyon/fluvio#962]
The process for upgrading a local cluster is to stop the current cluster and start a new cluster at a new version.

Data is lost when the initial cluster is stopped. We want to provide the capability of running local clusters that can keep data while upgrading from one version to another.

- [x] #4136
- [x] #4137

**Comment by digikata** [comment]
Some background which to focus this issue a bit more:

https://github.com/infinyon/fluvio/pull/3999 - added some good protection from accidentally upgrading local cluster versions  (e.g. a `fluvio cluster start` - local start with one version of fluvio,  `fluvio cluster shutdown`, a fluvio version upgrade occurs, `fluvio cluster resume` with a new version)

Adding a code path to run local data upgrade logic when a version difference is detected on `fluvio cluster resume` would allow some upgrade logic to be specified. 

Disallowing many configuration changes on `resume` will simplify this process. e.g. if the initial cluster was started with 2 spus, a resume should only be initialized with the former spu count, and no path to change the option on resume should be given.

Since most metadata updates are additions of fields, upgrade logic for this kind of change will mostly be reading all older data and ensuring deserializing works with a new default. 

More complex upgrades should be accommodated later on a case by case basis - but probably triggered on different specific version boundaries. (either semver based boundaries, or specified versions in the upgrade code).

**Comment by digikata** [comment]
The most basic use case to support is to allow version upgrades between known good versions -e.g. 0.11.10 -> 0.11.11
