### ISSUE TITLE
FLUVIO_CMD=true  doesn't seem work

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio#968]
Setting `FLUVIO_CMD=true` was used to display command arguments.  This is needed to debug installation process

```
FLUVIO_CMD=true cargo run cluster start --local --develop 
   Compiling fluvio-command v0.2.1 (/home/ubuntu/fluvio/src/command)
   Compiling fluvio-cluster v0.7.2 (/home/ubuntu/fluvio/src/cluster)
   Compiling fluvio-cli v0.5.1 (/home/ubuntu/fluvio/src/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 12.26s
     Running `target/debug/fluvio cluster start --local --develop`
Performing pre-flight checks
✅ ok: Supported helm version is installed
✅ ok: Supported kubernetes version is installed
✅ ok: Kubernetes config is loadable
✅ ok: Fluvio system charts are installed
Error: 
   0: Fluvio cluster error
   1: Fluvio cluster error
   2: Failed to install Fluvio locally
   3: Kubernetes client error
   4: client error: 409 Conflict
``

**Comment by nicholastmosher** [comment]
@sehz this functionality is still included, but the command is now printed to the debug log. In order to see the output, you'll need to run:

```
$ FLUVIO_CMD=true RUST_LOG=debug cargo run --bin fluvio -- cluster run start --local --develop
```

Actually now that I think about it, since it is being printed on `debug`, we probably should not require the `FLUVIO_CMD` environment variable to be set at all. I think that was just included in the past to not pollute standard output.

If you're ok with it, I can make a PR to remove the FLUVIO_CMD requirement and just always print command strings on `debug` when they are run. How does that sound?

**Comment by sehz** [comment]
Sure.  Can you remove that flag everywhere it is being used?

**Comment by sehz** [comment]
remove critical flag since there is work around
